mit-dci/utreexo

cmd/simcmd/sim.go
Fixes the problem with program not running unless you give it 3 arguments. Also fixes the [2:3] array issue.
Sorry for the simple dumb mistake. This fixes them.
=> Fix minor error in sim.go

cmd/blockparser/blockparser.go, cmd/blockparser/ttldbgen.go, cmd/ibdsim/histogram.go, cmd/ibdsim/ibdsim.go, cmd/simcmd/sim.go, cmd/txottl/txottlparse.go
Adds stop and resume for blockparser.
Behavior:
1) Builds `offsetfile` && `currentoffsetheightfile` first. "offsetfile" stores the 8 byte info of `.dat file num` and `offset`. `currentoffsetheightfile` is the tip from the offsetfile since there are is no tipnum saved to it. This is a cheaper way of doing that. If offsetfile is found, that file is used for syncing. If not found, it will build one. If there was more blocks synced by Bitcoin Core afterwards, simply delete the `offsetfile` and `currentoffsetheightfile` and it will build a new one based on the new .dat files given. Haven't tried with the full chain yet but it shouldn't take more than a minute at most.
If SIGINT, SIGTERM, or SIGQUIT is passed while building the two files, it will delete them since they are incomplete. 
2) …
=> Add stop and resume feature for parseblock

cmd/blockparser/blockparser.go, cmd/blockparser/ttldbgen.go, cmd/ibdsim/ibdsim.go, cmd/simcmd/sim.go, cmd/txottl/txottlparse.go
Now flag -testnet=true will handle things. No need to do ttlfn=ttl.testnet.txos now.
RawHeaderData Struct is also organized. 
It also added wg to stopParse() but not sure if that does anything.
=>  Fixed go-lint, added testnet flag, made stopParse wait for ttldb

cmd/ibdsim/genproofs.go, cmd/ibdsim/ibdsim.go, cmd/ibdsim/ttldb.go, cmd/utils/types.go, cmd/utils/utils.go
Goroutine added for ReadRawBlockFromFile() with Blockreader() inside utils.go
Benchmark shows around 12% improvement when run 
```./simcmd genproofs -testnet=1 && ./simcmd ibdsim -testnet=1```
compared to the old way.
=> Added goroutines for reading blocks off the .dat files

cmd/ibdsim/genproofs.go, cmd/ibdsim/ibdsim.go, cmd/ibdsim/offsetfile.go, cmd/utils/paths.go
Structed the files. 3 directories for the files are now created.
offsetdata/,  proofdata/, and forestdata/ are now created and all
relevant files are stored in each of the directories.
Helps with organization.
=> Add paths for the files.

cmd/ibdsim/genproofs.go, cmd/ibdsim/ibdsim.go, cmd/ibdsim/offsetfile.go, cmd/utils/paths.go, utreexo/forest.go, utreexo/forestdata.go, utreexo/pollard.go, utreexo/utils.go
Added functions to resume forest when using disk.
Cleaned forestdata.go and forest.go functions so they don't open up
files. Moved all the file opening functions to cmd/
So this works but is *painfully* slow.
=> Disk resume and remove opening files in Lib

utreexo/forest.go, utreexo/forestdata.go, utreexo/hasher.go, utreexo/pollard.go, utreexo/pollard_test.go
this stops use of floorTransform for forest Modify (still used in Undo, but can get rid of that later) and uses swapRange to move linear runs of hashes at once, hopefully speeding things up.
=> add swapRange to forest data and removev4

cmd/ibdsim/client.go, cmd/ibdsim/genproofs.go, cmd/ibdsim/offsetfile.go, cmd/ibdsim/server.go, cmd/simutil/paths.go, cmd/simutil/utils.go, utreexo/forest.go, utreexo/pollardutil.go
Fixes a off-by-one bug and saves and restores the current offset
of pOffsetFile. Also removes some fmt.Sprintf()s that were massively
slowing the stop and resume.
=> cmd/ibdsim: Fixed errors preventing from resuming genproofs

utreexo/pollardutil.go
So there is a pretty big typo where you call the function auntable() as auntOp. Not sure if you like to have a bunch of commits for one line changes so this could be fixed in the next big(er) thing too.
=> Fix auntable() comment

cmd/ibdsim/genproofs.go, utreexo/forest.go
Changes RestoreForest() from a method to a function
No longer relies on calling newForest() in cmd/
Addresses the comment by @adiabat on #68
=> utreexo/forest.go: Changes to RestoreForest()

utreexo/pollard.go, utreexo/pollardfull_test.go, utreexo/pollardutil.go, utreexo/pollarfull.go
This lets pollard do everything forest does.
Pollard now has a positionMap to track where hashes are within the forest.  It can provide proofs via GenProof, the same way forest does.
`NewFullPollard()` creates a pollard with the map enabled.  It will give errors or maybe crash if you try to use ProveBlock on a pollard that doesn't have a map.
Given this, you could technically delete all the Forest struct / methods / code.  There isn't an obvious way to keep the pollard on-disk though, so forest still does that.  Not sure which is faster though, an in-memory forest or a full pollard.
=> Allow Pollard to generate proofs

cmd/ibdsim/genproofs.go, cmd/ibdsim/offsetfile.go
During genproofs, when offsetfile was being built, user interruptions
were ignored. Fixes this.
=> cmd/genproofs.go: Fix bug where user interruptions didn't quit

utreexo/blockproof.go, utreexo/blockproof_test.go
VerifyBlockProof would quit before checking the calculatedTop
against the actual forest top. The main loop would quit before
checking all the heights as the main for loop needed to be <= not <
=> blockproof.go: Double spending bug fixed (creds to ysangkok)

utreexo/forest.go, utreexo/forest_test.go
Just a simple test asserting that we get an error
if we try to delete a leaf from an empty tree.
This test is currently consuming a lot of memory and does not pass.
=> forest_test: Add test deleting from empty tree

cmd/bridgenode/chain.go, cmd/bridgenode/chainio.go, cmd/bridgenode/genproofs.go, cmd/bridgenode/offsetfile.go, cmd/csn/client.go, cmd/csn/ibdsim.go, cmd/csn/server.go, cmd/main.go, cmd/ttl/ttldb.go, cmd/ttl/ttlparse.go, cmd/util/compress.go, cmd/util/paths.go, cmd/util/rev.go, cmd/util/rev_test.go, cmd/util/types.go, cmd/util/utils.go
Please do test out the rev_test.go file. You do need to copy rev*.dat files to the util/ directory for the test to work.
=> Refactor cmd/ and add rev*.dat block reading capability to util/

utreexo/forest.go, utreexo/forestdata.go, utreexo/undo.go, utreexo/undo_test.go
Seems like the main problem was the `cleanup` function... getting rid of it fixed all the problems with undo.
There are still a whole bunch of useless reads and writes of empty data (32 bytes of 0s) happening, so could look into those and stop that to speed up i/o.  But they don't look like they break anything.
=> Fix undo tests

cmd/util/compress.go, cmd/util/rev.go, cmd/util/rev_test.go
Fixed a bug in RevOffset generation and another in decompressing the
PKscript.
=> util/: Fix rev.go and compress.go

utreexo/forest_test.go
This is causing a panic on master.
I have let the commit message note the commit ID of master as it is currently, so that the fix can be merged first, if you like. That way, the commit description will still make sense.
Note that if you add another leaf, it still panics with the same error message. I am saying this because I suspected it was because of emptying the tree. But it seems it wasn't.
=> Add test deleting keys 1,0 from two-leaf tree

cmd/util/utils.go
This will let users know that they're missing rev*.dat files
=> util/utils.go: Panic when rev*.dat files are not present

bridgenode/genproofs.go, bridgenode/server.go, csn/client.go, util/types.go, util/utils.go
the genproofs side listens, and the ibdsim side connects.
Should be pretty straightforward as both sides are already using worker routines to get data off disk and put it in a channel; now it's just the function that feeds the channel is getting the data over the network instead of from the disk.  
Initially it will be real simple, just getting everything in order, with no real messages about which blocks to get.
=> WIP client / server networking

accumulator/utils.go
The util function `dedupeSwapDirt` currently does not work as intended/documented.
https://github.com/mit-dci/utreexo/blob/cb5c021b3d001a5f5b4dd3eedce8aac034a5dbd2/accumulator/utils.go#L389-L392
Example:
```go
dedupeSwapDirt([]uint64{1, 4, 5, 10, 16}, []arrow{{1, 4}, {1, 11}, {1, 16}})
```
This currently results in `[1 4 5 10 16]` but it should result in `[1, 5, 10]`.
=> accumulator: make dedupeSwapDirt work as documented

accumulator/forest.go
I must admit I don't understand the logic for this complicated branching logic. But I thought I'd propose this simplification. If it can't be simplified, would be nice to explain the logic.
=> Remove complicated branching in makeDestInRow

bridgenode/offsetfile.go, util/utils.go
* Regtest has its own magic bytes
* only 28 bytes were read when reading previous blockhashes from blk.dat files.
=> Fix regtest panic

util/rev_test.go, util/utils.go
```rev_test.go``` still needs an rev00000.dat file copied to the directory though. Could fix that with options for paths.
=> utils: Fix rev_test and error in util function

accumulator/forest.go, accumulator/utils.go, bridgenode/chain.go, bridgenode/chainio.go, bridgenode/offsetfile.go, csn/chainio.go, util/rev.go, util/ttl/ttl.go, util/types.go, util/utils.go
In an effort to reduce the util code...
The std library has all the functionality needed to convert integers to bytes and vice versa.
* In some cases this gets rid of the extra allocation, when converting to bytes.
* makes the code more readable (at least in my opinion)
=> util: Refactor integer conversion functions

accumulator/forest.go
Before this commit, updateDirt would return an unsorted slice,
which would then be passed back into updateDirt. Then,
dedupeSwapDirt would be called with its invariant violated.
So instead of the half-hearted checking of the last element,
we simply do a binary search (cheap) and insert the element
where it should be. No special treating of the last element.
=> updateDirt maintains sortedness

bridgenode/genproofs.go
Fixes the problem mentioned here: https://github.com/mit-dci/utreexo/pull/144#issuecomment-640761200
=> bridgenode: Dont start the blockServer if genproofs was paused

accumulator/forest.go, accumulator/forestdata.go
Adds a new type `cacheForestData` that implements the `ForestData` interface. This type improves the performance of `diskForestData` by caching parts of the forest in ram.
The cache holds a certain number of trees of the full forest while the other trees are kept on disk, the trees kept in the cache are the smallest trees in the forest. The whole forest might be held in ram when the cache size allows it.
Usage:
```go
d := new(cacheForestData)
// 16 means that the 16 smallest trees will be cached.
// that's only about ~4MB, 17 would be ~8MB, 18 -> ~16MB, ..., 27 -> 8448MB, ...
d.cache = newDiskForestCache(16)
d.f = forestFile
```
=> accumulator: Add a cache for disk forest data

bridgenode/offsetfile.go, bridgenode/offsetfile_test.go, bridgenode/rev.go, util/types.go, util/utils.go
Offsetfile building but now with buffers. In my machine, sys and user time is 80% less but the wall clock is only showing 30% less time :/ I guess there's some serious disk io bottleneck going on that *could* be improved with more effort. Just not sure if it's worth the effort.
Benchmark added in offestfile_test.go and also fixes a test in offsetfile_test.go which was broken in master. We could also start to use the tests here...
=> offsetfile: Buffer the leveldb, reader, and writer for offestfile

bridgenode/rev.go
Problem: the `BlockAndRevReader` makes a ton of syscalls because it reads each block individually from the blk files.
Solution: read multiple blocks from the blk files at once.
pprof results:
Before: 
After:
=> bridgenode: Improve BlockAndRevReader performance

bridgenode/offsetfile.go, bridgenode/rev.go
fixes the `unexpected EOF` crash at the end of genproofs.
=> offsetfile: Ignore blocks that don't have undo data

.gitignore, accumulator/batchproof.go, bridgenode/genproofs.go, bridgenode/rev.go, bridgenode/server.go, util/types.go, util/utils.go
The server would previously read blocks & udata from disk, deserialize them into data structures and then re-serialize them onto the network.  This PR changes the server so that it blindly reads bytes from files on disk and then sends them out over the network.
In the process I think I changed some of the serialization, like what length prefixes things have, so this may require a rebuild of the proof file, which means re-running utreexoserver from scratch.  Maybe not but if anything goes wrong that's the first thing to try.
=> Stop server from looking at the data it's serving

accumulator/hasher.go, accumulator/pollard.go
Two things are changed:
1. Pollard no longer generates goroutines per parentHash in rem2. The
bottleneck would come from the go scheduler deciding which goroutine to
run. Resulting in the scheduler block being longer then the execution
time. This also solves the datarace issue where duplicate hashes would
be made
2. Gets rid of fmt from grabPos. This is helpful for reducing the gc
latency as every fmt is a heap allocation.
=> accumulator: More efficient pollard

accumulator/batchproof.go, accumulator/pollard.go, accumulator/pollardproof.go, accumulator/types.go, csn/ibd.go
Things done:
1. Different implementation of #3 where the already known hashes of parents were matched, saving sha256 hashes. Instead of going through all the nodes to the path of the leaf being verified, in this implementation just looks for the polNode at the parent position. New method on pollard ```readPos``` was needed as reading from ```grabPos``` created nil hashable nodes.
2. Various comments and small code fixes.
In my testing to block 600,000 on testnet3, the speedups were around 5%. However, when tested on blocks with lower height, the speedups were even less. So more hashing goes on as the tree gets bigger, leading to bigger savings. The matched hashes to the tip of the default server was 160,716,082 hashes and the unmatched hashes were 55,700,940 hashes. So this is around 75% …
=> accumulator/pollard: Speedups for pollard

accumulator/utils.go, accumulator/utils_test.go
```treeRows``` is called fairly often and from pprof results, treeRows is fairly high in the list of time taken. The current implementation is just bit shifting. I've implemented as:
1. Find the next power of 2
2. Take the log2 of that number
From this, I've gone ahead and implemented some bit tricks to really optimize it. 
With the new implementation (thanks @dergoegge) treeRows now only takes ~2% of the time it originally took. My benchmarks are done on a laptop so it's not as good but the results from benchstat are:
```
[I] calvin@bitcoin ~/b/u/g/s/g/m/u/accumulator> benchstat old.txt new.txt
name                    old time/op  new time/op  delta
OrigTreeRows_HunThou-4  0.00ns ±19%  0.00ns ±13%   -98.51%  (p=0.008 n=5+5)
OrigTreeRows_Mil-4      0.02ns ± 1%  0.00ns ±13%   -97.71% …
```
=> accumulator/utils: Much much faster treeRows

bridgenode/genproofs.go, cmd/utreexoclient/csnclient.go, cmd/utreexoserver/bridgeserver.go, csn/init.go
Adds a flag to enable tracing, a tool in the go standard toolchain. https://golang.org/cmd/trace/
=> cmd: Add tracing flags for the client and the server

accumulator/utils.go
My first commit, I'll keep it short. 
The benchmark results,
```
go test -run=XXX -bench=BenchmarkNumRoots
goos: darwin
goarch: amd64
pkg: github.com/mit-dci/utreexo/accumulator
BenchmarkNumRootsOld-4   	16488475	        69.8 ns/op
BenchmarkNumRootsNew-4   	1000000000	         0.410 ns/op
PASS
ok  	github.com/mit-dci/utreexo/accumulator	1.685s
```
The code,
```go
func BenchmarkNumRootsOld(b *testing.B) {
for i := 0; i < b.N; i++ {
numRootsOld(1 << 63)
}
}
func BenchmarkNumRootsNew(b *testing.B) {
for i := 0; i < b.N; i++ {
numRootsNew(1 << 63)
}
}
```
=> accumulator: use bits.OnesCount64

accumulator/types.go, util/types.go
I tested this up until block #300000 and sha512 seems to be a bit faster. (1.3x faster in my test)
[pprof_files.zip](https://github.com/mit-dci/utreexo/files/5126671/pprof_files.zip)
=> accumulator: Use sha512/256 instead of sha256

accumulator/pollard.go, accumulator/pollardproof.go, accumulator/pollardutil.go, accumulator/utils.go
There was a bug in `addOne` that made the pollard not remember a leaf, see #180 for details.
This PR also refactors the roots to be pointers to `polNode` and makes readPos not stop at nil siblings.
=> pollard: Make addOne remember leaf siblings correctly

bridgenode/chainio.go, bridgenode/genproofs.go, bridgenode/server.go, cmd/utreexoserver/bridgeserver.go, test/install_bitcoind.sh
This PR should help with faster testing as the server binary can build a small number of proofs, quit, and then start serving them.  Generating the proofs and serving them are pretty independent things and this helps pull them apart.
=> Split proof building and serving functions

accumulator/batchproof.go, accumulator/forest_test.go, accumulator/forestproofs.go, accumulator/pollardproof.go, accumulator/pollarfull.go, accumulator/utils.go
was part of my experiments in #180.
Refactor `ProveBatch`, `verifyBatchProof` and `IngestBatchProof` to use slices.
Preallocation of slices also helps with GC pressure. 
also includes the `ProofPositions` function which is also part of #185, kinda stupid but otherwise this doesn't build.
=> refactor: Use slices instead of maps

bridgenode/genproofs.go, bridgenode/server.go
Leveldb compression is slowing down client serving. I know flatttl is coming but this is a no-brainer simple change that results in massive speedups.
We're already giving the same option for rev leveldb https://github.com/mit-dci/utreexo/blob/b3afd5d7a3f0fc297c2ce1d936b6bf87edd6fd61/bridgenode/rev.go#L400
=> bridgenode: Don't use compression for leveldb

accumulator/pollard.go, accumulator/utils.go
`descendToPos()` was only used in `toFull()`. Gets rid of `descendToPos()` and uses `readPos()` inside `toFull()`.
Partially addresses #211
=> accumulator/pollard: Get rid of descendToPos

accumulator/batchproof.go, accumulator/pollard_test.go
See commit message for explanation.
I checked with the previous map based verification and the same problem existed there:
https://github.com/mit-dci/utreexo/blob/573edd2bb6d34f7073873e617c13c056e745d658/accumulator/pollardproof.go#L177-L194
`parhash` is considered to be equal to the result of `parentHash(...)`.
The main problem here is that the roots are always cached and therefore the roots computed from the proof are never actually compared to the actual roots.
=> accumulator: Fix batch proof verification

accumulator/utils.go
when h is 0, there would be multiple underflows. This gets rid of that
=> accumulator/utils: Get rid of two underflows in rootPosition

bridgenode/flatfileworker.go, bridgenode/genproofs.go, util/types.go
The offset of the last written proof was saved which caused an off-by-one on restart because that last proof is over written by the next block.
Closes #216
=> Fix bridge restart

.github/workflows/go.yml
Github is deprecating 'add-path' and 'set-env' because of vulnerabilities.
Updates to the new recommended functions.
More info [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) about the deprecation
=> .github/go.yml: Update Github Actions

csn/ibd.go
The ttl values being send now are actually the ttls not heights, so the
subtraction is not needed anymore.
Also @adiabat since the verification logic got changed the `overWire` variable is currently not used but the place to collect the positions for the playbooks would be in the **else** branch [here](https://github.com/mit-dci/utreexo/blob/760cec1adc9aceb112ed16e6343ee06135e098a8/accumulator/pollardproof.go#L78) and [here](https://github.com/mit-dci/utreexo/blob/760cec1adc9aceb112ed16e6343ee06135e098a8/accumulator/pollardproof.go#L86). 
`p.populate` is called for every root that was involved in the verification, so what you need to do to get all the "overwire" positions for the entire proof is: collect the "overwire" positions in each populate call and then concat all these together, …
=> csn: Use ttl not ttl - height

accumulator/hasher.go
EDIT: sha512 was not the culprit, it was the goroutines.
`hashOne()` was taking up 22% of the overall sync time from my tests up to height `150,000` on mainnet.
This slowdown is mostly caused by the heap allocations that each of the goroutine makes. Each makes 4096bytes of stack so over time this builds up a lot. Solution was to just get rid of the goroutines.
Profiling for the new code looks like so. `root` takes 142.15 seconds. Note how long the `hashRow()` function takes. This is with the individual hashes counting towards the overall time (since there is no more goroutines).
Compared to the old profile here, where the `root` takes 250.44 seconds. Note how the `hashRow()` function takes longer, not counting the actual individual hashes.
=> accumulator/hasher.go: Faster hashrow

accumulator/batchproof.go, accumulator/batchproof_test.go
If the number of proof positions (+number of targets) does not match the number of provided hashes the proof is invalid.
=> accumulator: Check number of proof hashes

accumulator/forestdata.go
I ran into this on the test server:
```
panic: open /home/niklas/go/src/github.com/mit-dci/utreexo/cmd/utreexoserver/utree/forestdata/cow/56956.ufod: too many open files
goroutine 1 [running]:
github.com/mit-dci/utreexo/accumulator.(*cowForest).read(0xc00010e1b0, 0x3da0000, 0x0, 0x0, 0x0, 0x0)
/home/niklas/go/src/github.com/mit-dci/utreexo/accumulator/forestdata.go:715 +0x529
github.com/mit-dci/utreexo/accumulator.(*Forest).reMap(0xc000012840, 0x981f1a, 0x20, 0xc0b33ce800)
/home/niklas/go/src/github.com/mit-dci/utreexo/accumulator/forest.go:530 +0x311
github.com/mit-dci/utreexo/accumulator.(*Forest).Modify(0xc000012840, 0xc0cda4e000, 0x4c1e, 0x5b26, 0xc0c8ae6c00, 0x15f, 0x15f, 0x15f, 0x15f, 0xc0cdbcc000)
/home/niklas/go/src/github.com/mit-dci/utreexo/accumulator/forest.go:466 +0x1ff …
```
=> cow: Make sure to close files after use

bridgenode/flatfileworker.go, bridgenode/genproofs.go, bridgenode/processblock.go, bridgenode/rev.go, cmd/utreexoserver/bridgeserver.go, csn/ibd.go, go.mod, go.sum, util/utils.go, wire/umsgblock.go
btcutil.Block on the utcd repo caches hashes so that you only hash a
tx once per block instead of numerous times. This helps speed up the
genproofs on bridgenode and the ibd on csn
Setting gcpercent at 20 helps with excessive memory usage when loading
thousands of blocks from disk.
=> bridgenode: Use btcutil.Block instead of the raw msgBlock

bridgenode/config.go, bridgenode/server.go, cmd/utreexoserver/bridgeserver.go
Adds a flag to enable live pprof http server. Also fixes the memprof
so that the memory profile taken is done at exit not at the start
=> bridgenode: Add http server for profiling and fix memprof

accumulator/batchproof.go, accumulator/forest.go, accumulator/forestproofs.go, accumulator/pollard.go, accumulator/pollard_test.go, accumulator/pollardfull.go, accumulator/pollardfull_test.go, accumulator/pollardproof.go, accumulator/pollardutil.go, accumulator/utils.go
Changes made:
getRootsReverse forces unnecessary allocations as the roots are
appended to a new list. This helps reduce the amount of memory
allocations, resulting in less time taken up by the gc.
Also, grabbing roots forwards is a lot cleaner than the reverse method.
Positionlist (aka slice of uint64) is used numerous times in the accumulator code. Having a freelist for this list reduces gc pressure.
All the functions that use computedPositions only take the length of the computedPositions slice. Changing this to just a int64 reduces gc pressure and speeds up the code.
=> accumulator: Change getRootsReverse to getRootsForwards and add a freelist for positionlist

accumulator/forest_test.go, accumulator/forestdata.go, accumulator/forestdata_test.go, bridgenode/config.go
Things done:
1. Add caching strategy to cowForest.It has a slightly better caching now. cowForest treeBlocks (subtrees) now have a height of 1 (3 leaves). This makes the cowForest **not** backwards compatible with a previously saved cowForest.
2. Add stats for treeTable hits/misses. (misses are very low).
3. Add a test for writing the cowforest (tests flushes as well).
4. Flag for cowmaxcache now in MB instead of treeTable max count.
=> accumulator/forestdata: Improvements to cowforest

accumulator/pollard.go
There was a bug in where the slice allocation was appending empty
(filled with 0s) slices. Fixes this.
=> accumulator/pollard: Fix slice allocation

bridgenode/config.go, bridgenode/dbworker.go, bridgenode/error.go, bridgenode/genproofs.go
One of the main bottlenecks for utreexoserver is the ttldb. Reads/writes
every block slow genproofs down by a lot. This PR adds an option to have a cache
of the ttldb with the flag `memttldb`. There is also the option to keep the entire ttldb in memory with the 
flag `allttldbinmem` for if you have enough ram.
=> bridgenode: Add an option for keeping the ttldb in memory

accumulator/batchproof.go, accumulator/pollardproof.go
The past `populate()` function was slow as it would traverse the tree numerous times to populate a node. This new algorithm starts from the root and populates the pollard row-by-row.
Previously, what the `populate()` function would do unnecessary loops as there were no information about where the next `miniTree` (aka `[3]node`) would be.
It would:
1: Pick a node in the pollard.
2: Keep looping through all the existing unpopulated `trees` until we find it.
3: Loop until we've found all of the corresponding positions for the `trees`.
Because of this, there would be a lot of misses, leading to a slow `populate()` algorithm.
In this new `populate()` algorithm, I'm introducing two functions `nodesToFollow()` and `nextNodes()` which grab the nodes that we have to follow of the row below, …
=> accumulator: new populate algorithm

accumulator/types.go, btcacc/leaf_test.go, btcacc/udata.go
Adds test for leafData serialization. Also removes the additional check
that's done for udata during SerializeSize() as it is very costly.
=> btcacc && accumulator: Update comments and remove some costly checks

accumulator/batchproof.go, accumulator/batchproof_test.go, accumulator/forest_test.go, accumulator/forestproofs.go, accumulator/pollard_test.go, accumulator/pollardfull.go, accumulator/pollardfull_test.go, accumulator/pollardproof.go, accumulator/utils.go, btcacc/udata.go, csn/ibd.go, go.mod, go.sum
Before, the target hashes also used to be included in the BatchProof.
However, these are just the hash commitments of elements to prove and
the user has all the data needed to calculate the hashes.
Removing them achieves two things: smaller proofs, simpler verification.
Since the hashes no longer is being stored, the proofs get smaller by
however many deletions that are to happen. The verification logic is
simpler as it no longer has to have extra logic to separate out the
target hashes from the actual proofs.
=> accumulator/batchproof: Remove target hashes from BatchProof

bridgenode/config.go, cmd/utreexoclient/csnclient.go, csn/config.go, csn/ibd.go, csn/init.go
Adds a profiling server flag for `utreexoclient`, which helps in getting snapshots of memory usage during when the binary is running. Also for `utreexoclient` now the memory profile snapshot is correctly taken during when the binary exits.
For `utreexoserver`, it now turns on `memttldb` flag when `allttldbinmem` flag is given. Before, you could give the `allttldbinmem` flag by itself and it would do nothing because the `memttldb` flag hasn't been given, which is not intuitive.
=> cmd: Minor changes to utreexoserver and utreexoclient

bridgenode/processblock.go, csn/ibd.go, go.mod, util/utils.go, wire/umsgblock.go
Use local DedupeBlock() to remove utcutil and utcd dependency. The
utreexo repository is now only dependent on the default btcd repository.
DedupeBlock() now also returns the count of all the inputs and outputs.
This let's callers pre-allocate slices to the required length improving
memory allcation efficiency.
This will make the `utreexoclient` and `utreexoserver` binaries a bit slower since they are now linked to the btcd repo without all the performance improvements I have added in. The eventual plan would be to link it to utcd, when things are a bit more stable.
=> util/util, csn, bridgenode, wire: Use local DedupeBlock()

accumulator/pollard_test.go, accumulator/pollardutil_test.go
This works on the issue of  #295 
function PollardSerializeDeserialize() generates a pollard and serializes it and then deserailizes it  keeping account of the bytes count of the previous serialization.
The desearialized pollard is serailized again and the bytes obtained is compared with the previous serialization bytes.
If equal the test passes .
function TestPollardSerializeDeserialize() performs the testing
=> Pollard test for serialize and deserailize 

accumulator/batchproof_test.go, accumulator/forest.go, accumulator/forest_test.go, accumulator/forestdata_test.go, accumulator/pollard.go, accumulator/pollard_test.go, accumulator/readme.md, accumulator/undo_test.go, bridgenode/initrestore.go, bridgenode/processblock.go, csn/ibd.go, go.mod, util/utils.go, wire/umsgblock.go
Solves issue #294
Uses an enum as a receiver to the function `NewForest`
```go
const (
DiskForest ForestName = iota
RamForest
CacheForest
CowForest
)
```
Earlier the new forest function used function arguments to infer which type of forest is to be initialized
```go
if forestFile == nil {
if cowPath == "" {
// for in-ram
f.data = new(ramForestData)
} else {
// Init cowForest
d, err := initialize(cowPath, cowMaxCache)
if err != nil {
panic(err)
}
f.data = d
}
} else {
// forest on disk or cached
if cached {
d := new(cacheForestData)
d.file = forestFile
d.cache = newDiskForestCache(20)
f.data = d
} else {
// for on-disk
d := new(diskForestData)
d.file = forestFile
f.data = d
}
}
```
Now the implementation has been made like this
```go
switch fn {
case DiskForest:
d := new(diskForestData) …
```
=> ref: NewForest function to use enums for forest types

readme.md
Fixes a small typo in the "Importing Utreexo" section of the readme file: `speicifc` -> `specific`
=> readme: fix typo in Importing Utreexo section

accumulator/types.go
Previously, the left and right Hash slices were appended and then passed off to the hash function. This new hash method saves on the memory allocation that would have happened with the append by writing to the digest directly.
Below are the memory profile before and after the change in `parentHash()`. The test was done with `utreexoclient`  getting blocks locally from `utreexoserver` up to block #522315.
Before:
After:
We end up saving about a gig of memory allocations.
=> accumulator/types: Less memory allocation for parentHash()

bridgenode/config.go, bridgenode/offsetfile.go, csn/config.go, util/utils.go
This PR is supposed to add support for SigNet [🔗](https://en.bitcoin.it/wiki/Signet) to facilitate a smaller and simpler development environment.
EDIT: 
This PR will enable users to test and develop utreexo on very minimal system requirements. The total storage space required for signet is `190MiB` and the size of .utreexo/signet is `132MiB`.
=> add support for signet

accumulator/undo.go, bridgenode/config.go, bridgenode/flatfileworker.go, bridgenode/genproofs.go
This PR is for saving the undoblocks data returned from forest.Modify from the BuildProofs function in the genproofs.go file.
A new channel of undo unBlock type has been created where the undoblocks are passed which is then sent to flatfileworker .
a new parameter for undoBlocks height is added
config for undoBlock directory is added
=> Saving UndoBlocks in Undoblock directory

accumulator/pollard.go, accumulator/pollard_test.go, accumulator/pollardutil.go
This PR is related with #287
EDIT:
Second commit adds pollard size to the stats, making it easier to keep track of the pollard size.
=> Fix random polNodes sticking around

accumulator/batchproof.go, accumulator/batchproof_test.go, accumulator/forest_test.go, accumulator/forestproofs.go, accumulator/pollardproof.go
Now the verifyBatchProof function returns an error instead of a bool to
denote that a proof has failed to validate. If the proof validates, a
nil is returned. If it doesn't, an error with a helpful error message
will be returned.
There may be various reasons for verifyBatchProof to fail but the
message that the caller got was just a bool. Returning an error when the
proof fails allows more information to be tranferred to the caller.
=> accumulator/batchproof: Error instead of bool for verifyBatchProof

bridgenode/config.go, bridgenode/flatfileworker.go, bridgenode/genproofs.go
In this PR a new config for ttl directory has been added and ttl data are being stored in a new flatfilestate in the flatfileworker.go
=> Saving TTL data seperately

.github/workflows/go.yml, .gitignore, accumulator/fuzz.go, accumulator/types.go, accumulator/undo_test.go, go.mod, go.sum
TODO:
A simple fuzzer using [go-fuzz](https://github.com/dvyukov/go-fuzz).
- implement a fuzzer for forest / undo
- add a check that undo produces the same roots that were there before the block
This is probably not optimal - i.e. the execution time of each try could be reduced.
It also doesn't cover all of the branches after about 12 hours of CPU time - can be seen in the coverage.
Usage:
```shell
go install github.com/dvyukov/go-fuzz/go-fuzz@latest
go get github.com/dvyukov/go-fuzz/go-fuzz-dep
cd accumulator
go-fuzz-build
go-fuzz
```
Coverage:
```shell
go-fuzz -dumpcover
go tool cover -html=coverprofile
```
=> Fuzz forest / undo

accumulator/pollard_test.go, accumulator/pollardfull_test.go, accumulator/pollardproof.go, csn/ibd.go
IngestBatchProof now takes in a `rememberAll` argument. When it is
true, IngestBatchProof will mark all of the proof to be remembered.
The functionality is tested by a new function,
`TestPollardIngestMultiBlockProof` which has the forest generate proofs
in a certain interval.
NOTE: There hasn't been much testing to check that all nodes that should
be forgotten have been forgotten after the pollard is done deleting all
the nodes the proof was for.
Furthermore, there needs to be code to forget the proofs if the
batchproof was lying about what leaves will be deleted in the future.
=> accumulator/pollard: Add support for multi-block proofs

accumulator/forest.go, accumulator/forest_test.go, accumulator/forestproofs.go, accumulator/pollard_test.go, accumulator/undo_test.go
Function getroots is exported so that bridge nodes are able to query
the accumulator roots.
=> accumulator/forest: Export getroots function

accumulator/forestproofs.go
Previously f.data.size() was used to determine if there is only a single
leaf in the forest. The single leaf check is important as for a forest
with only 1 leaf, the leaf is the proof and a batchproof shouldn't be
generated.
f.data.size() returns allocated size ofthe entire forest, not the logical
size.  This means that if the forest allocates beforehand or reorgs back
to 0 leaves, the size check will fail and ProveBatch() will wrongly
generate proofs.
f.numLeaves always returns the logical number of elements in the forest,
avoiding this bug.
=> accumulator/forestproofs: Fix bug in ProveBatch()

accumulator/forestproofs.go
If the number of leaves is `numLeaves`, valid leaf positions are in the range of `(0, numLeaves-1)`, i.e. `pos == numLeaves` is already out of range. Take this into account for the sanity check before calling `detectSubTreeRows`.
=> accumulator/forestproofs: fix off-by-one error in `Prove` sanity check

accumulator/utils.go
This function hasn't been used since commit
e83f377a2a6f9c3287ef64d01eab1e02b3c27606. It seems that it was only useful for removev2 and earlier, i.e. it makes sense to get rid of it.
=> accumulator/utils: remove unused function `subTreePositions`
