utreexo/pollard.go, utreexo/pollard_test.go, utreexo/pollarutil.go
Seems to work -- there are still issues though; there are sometimes isolated leaves at the base of the tree, and there shouldn't be.
=> use slice instead of map to track dirty locations in pollard

utreexo/blockproof.go, utreexo/forest.go, utreexo/forest_test.go, utreexo/forestproofs.go, utreexo/pollard.go, utreexo/pollard_test.go, utreexo/pollardproof.go, utreexo/pollarutil.go, utreexo/types.go, utreexo/undo.go, utreexo/utils.go
Fixed the source being noted with go-lint.
golint utreexo/*.go
=> fixed go-lint

cmd/blockparser/ttldbgen.go, cmd/txottl/txottlparse.go, utreexo/types.go
Simple replacement of hash algorithms. I think it's slower but oh well.
=> Replace blake256 with sha256

cmd/blockparser/blockparser.go, cmd/blockparser/ttldbgen.go, cmd/ibdsim/ibdsim.go, cmd/simcmd/sim.go, cmd/txottl/txottlparse.go
I worked off the pull #28 for this one though. Can rebase onto master if #28 isn't good.
=> Add resume to txottl

readme.md
I've set up a github repo where logs are updated every day.
Link to that in the readme
=> Include link to freenode log

utreexo/forest.go, utreexo/forest_test.go, utreexo/forestdata.go, utreexo/forestproofs.go, utreexo/hasher.go, utreexo/pollard_test.go, utreexo/transform_test.go
the last PR didn't actually use the code, which didn't work.
This one uses the code, and it seems to work.
=> actually use swapRange

cmd/ibdsim/server.go
Now the UTXOs are given 1 << 30, which will prevent it from being saved
Fixes #44
=> Fixes the UTXOs having a negative duration.

cmd/ibdsim/client.go, cmd/simutil/paths.go, utreexo/forest.go, utreexo/pollardutil.go
Only stores the tops in pollard at the moment. Does resume though.
=> Add Pollard resume functionality.

cmd/ibdsim/client.go, cmd/simutil/paths.go, utreexo/forest.go, utreexo/pollardutil.go
=> Revert "Add Pollard resume functionality."

cmd/ibdsim/client.go, cmd/ibdsim/genproofs.go, cmd/simutil/paths.go, utreexo/forest.go, utreexo/pollardutil.go
Stores the tops for now. Re-requesting PR since the other one undid some of the work done on previous merged PRs.
=> Add Pollard resume functionality

readme.md
People wouldn't really know otherwise so it's probably good to mention it.
=> README: Mention resume functionality for Utreexo simulator

readme.md
Kanzure's setup has live updates while my logs only update every midnight. Far better logs.
=> Change the link for irc logs to kanzure's website

cmd/bridgenode/chain.go, cmd/bridgenode/chainio.go, cmd/bridgenode/genproofs.go, cmd/csn/client.go, cmd/csn/ibdsim.go, cmd/main.go, cmd/util/utils.go, readme.md
But caution, regtest is called TestNet in Lit.
(and testnet is called TestNet3)
For user-facing text, we use the 'regtest' name
to lessen the confusion.
=> Add Regtest support

cmd/clair/clair.go, cmd/clair/clairibdsim.go
Clair file updated and ibdsim using clair instead of lookahead.
Code doesn't compile without a few changes. PR as reference to the old clair system as talked about.
=> Add old clair files for reference

.github/workflows/go.yml
Fixes #61.
The test is currently failing, but that is because the repo is currently broken (as of 1f18fa8019131d45bd9de0f28c1e905ad4e2cf26), it is not because of this PR :)
=> Add Github Actions CI

utreexo/blockproof_test.go
In a two leaf tree, we prove one node, then delete the other.
This commit adds a test asserts that the proof for the first node
stops being valid after deletion of the other node.
=> blockproof_test: Test proof stops being valid

utreexo/forest_test.go
These forests have up to 256 leaves, generated using testing/quick.
The test is currently triggering another panic.
=> Add a test for random small forests

.github/workflows/go.yml
This makes the tests run again. Tested in my fork.
=> Fix YAML syntax in Github test configuration

accumulator/transform.go
Also removing the branching on mask since branching is more expensive and complicated than just doing the zero-XOR.
=> DRY in transform (new function swapInRow)

accumulator/pollardutil.go, accumulator/utils.go, bridgenode/genproofs.go, bridgenode/server.go, csn/chain.go, csn/client.go, util/utils.go
Suspend / resume for both client and server side
=> network v2

accumulator/transform.go
Might even be a bit faster since arrays are initialized to their correct size.
=> transform: Split up remTrans2

bridgenode/server.go
I saw this comment:
https://github.com/mit-dci/utreexo/blob/23d9af597ccf5175527483667e112d04fcdb7c67/bridgenode/server.go#L38-L40
and thought: why not move the accepting of new connections to its own goroutine and pass connections back to the select statement via a channel? that way the arbitrary timeout is not needed.
disclaimer: i did not test this, since i currently don't have a full node setup.
=> bridgenode: accept connections in separate goroutine

accumulator/forest.go
A bunch of commented code and hDestSlice was also removed. hDestSlice was equal to nextHashDirt as far as I could observe.
=> Forest: Split up removev4

bridgenode/genproofs.go, csn/ibd.go, test/csn_bridge.sh, util/utils.go
There were some small errors introduced with #148, which this PR fixes.
=> Fix errors introduced with #148

cmd/utreexoclient/csnclient.go, cmd/utreexoserver/bridgeserver.go
=> cmd: Add options for pprof

readme.md
Updated with the client/server stuff
=> Windows Documentation Added

cmd/utreexoclient/csnclient.go, csn/hook.go, csn/ibd.go, csn/init.go, csn/reload.go, test/csn_bridge.sh, util/paths.go
This PR adds a command line option to utreexoclient that takes a bech32 address and watches for it as it runs through IBD.
I figure that gives you something to watch while it's doing IBD which is otherwise kind of boring.
It could give a "balance", or list of existing utxos or something.
This seems like enough to show that a wallet could work, without having to write or attach an actual wallet.
=> watch address and report transactions

bridgenode/genproofs.go, csn/ibd.go, go.mod, go.sum, util/types.go, util/udata.go, util/utils.go
In my testing vs master to block #120,000, this branch syncs in ~4m50s vs master of ~8m20s.
This PR depends on changes to btcd code which I have made a PR on at https://github.com/Rjected/btcd/pull/1
=> csn: Faster IBD

bridgenode/genproofs.go, bridgenode/server.go, util/types.go, util/utils.go
(this allows requests for blocks out of order)
=> have client request each block separately

bridgenode/server.go, cmd/utreexoclient/csnclient.go, csn/hook.go, csn/ibd.go, csn/init.go, util/utils.go
note that this makes the server listen on the network interface!
so it's an actual server now, whatch out
=> Make server listen publicly and client can connect to specified host

util/paths.go
Supporting default Windows datadir
=> Updated paths.go

accumulator/utils.go
I think an example could provide some intuition on what this function is doing, since I didn't get it before I started working through the example I was given on IRC. I would understand if you think examples are not the best way to explain it, we could also put them somewhere else if you feel it is too verbose. But I submit it anyway, since I think it could help people randomly looking through the source, and I think it is better to be too verbose than too cryptic.
=> extractTwins example in comment

accumulator/transform.go
I added some parameter docs, and I tried adding an example, but it is mostly just a run through the function with example data for the first branch. Since it only covers one branch, I feel that the docs could still be improved. But I don't understand it all, so I submit what I have. I'd appreciate if someone could tell me whether they think this comment could improve comprehension. Maybe I should remove the example?
=> makeCollapse example in comment

accumulator/bittricks.md
=> docs: Add bittricks.md

cmd/utreexoclient/csnclient.go, csn/ibd.go, csn/init.go, test/csn_bridge.sh
=> test: Add csn resume test

accumulator/batchproof.go
Clean up of BatchProof.Reconstruct.
=> accumulator: Make BatchProof.Reconstruct use the ProofPositions function

.github/workflows/go.yml, bridgenode/genproofs.go, test/check_proofs_backwards.sh, test/csn_bridge.sh
Fetches the master branch and diffs the proof against the one generated by the PR.
It's currently breaking because the master binary doesn't have the flags I'm using in the script. Works after #215 is merged.
=> Actions: Compare proofs with master

test/csn_bridge.sh, test/install_bitcoind.sh
Currently tests are failing as it depends on this PR https://github.com/adiabat/adiabat.github.io/pull/4
Closes #255
=> test/: Update install_bitcoind script to fetch bitcoind v0.21.1

accumulator/pollardproof.go
Previously, polNodes that were to be newly allocated would be done so
through a slice. However, since Go gc doesn't garbage collect parts of
slices, most of the polNodes that were created were never garbage
collected. This resulted in the polNodes allocated taking up over 20GBs
on testnet3. This commit reverts the polNode allocation from done all
together as a slice to being done one at a time and not as a slice.
=> accumulator/pollard: Fix pollard memory leak

accumulator/pollardproof.go
Pollard now has a method just for verifying a given proof. This new
method does not alter the Pollard in any way, making it useful during
verifying mempool Bitcoin transactions.
Am looking for inputs in this because I'm thinking maybe we should take out the verification part from `IngestBatchProof()` and just have the caller call `Pollard.VerifyBatchProof()` for verifying, and call something like
```
// This function would force us to export MiniTree and Node, so might not be worth it.
func (p *Pollard) IngestBatchProof(trees []MiniTree, rootCandidates []Node) error {}
```
=> accumulator/pollard: Add a VerifyBatchProof method

readme.md
This fixes the documentation issue of #259 
Modified instruction of running server as necessary
=> fix readme about utreexo server

accumulator/forest.go, accumulator/forest_test.go, accumulator/utils.go
Refactors the test function for checking if forests equal and makes it
public. Equal function is useful for testing and general sanity
checking.
=> accumulator/forest: Add AssertEqual() to Forest
